language: node_js
node_js:
  - "4.1"
script: node_modules/karma/bin/karma start karma.conf.js --single-run --browsers Firefox
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install bower angular-mocks karma karma-jasmine jasmine-core karma-firefox-launcher karma-coverage
    - bower install